### PR TITLE
Logging JobManagerThread.getNextJob() logs only if debug is enabled

### PR DESCRIPTION
**Pull request by gmerinojimenez**
Hello,

This change just uses the JqLog.isDebugEnabled() method to don't log those messages if we're not in debug. I've made the change because I was getting [too many messages](https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/98619/2042406/wbpTIIX85BMkQ4d/Captura%20de%20pantalla%20de%202016-03-29%2011%3A02%3A35.png) in the logcat.

Please, don't hesitate to reply if you want me to change anything else.

Thanks for your time, best regards

### CODE REVIEW

**Comment by yigit** [comment]
you can set a null logger to disable these logs or completely disable debug logs. The only time JobManager checks is when the log requires some calculation. 
What is your use case? You want to enable logs except these lines?

**Comment by gmerinojimenez** [comment]
Yes, currently we've set a null logger, but we think that will be interesting to be able to log what happens inside JobManager. But the "looking for next job"/"non persistent result" are too frequent in our case and make hard to read the logcat.

**Comment by yigit** [comment]
I understand but this is not a perfect solution as the message queues also log a lot. Actually this log is useful. Maybe we can introduce **trace** level logs and move these verbose logs to there?
e.g. `JqLog.trace` ? wdyt?

**Comment by gmerinojimenez** [comment]
I like the idea, I will do the change if you agree. My only concern is that I'll need to modify the CustomLogger interface to add a trace method, which will force everyone to implement it in their projects, could we assume this?

**Comment by yigit** [comment]
yes we can because V2 is full API breaking changes and it is still alpha so it is last few days thats ok to break the API :).

**Comment by gmerinojimenez** [comment]
Ok then :)

I've updated the request, I've used _verbose_ mode instead of _trace_ to fit Android's Log, if you prefer trace, just tell me.

Also, if you want me to move the message queues logs too, please, tell me.

**Comment by yigit** [comment]
thanks. We can change them later, I'll merge this.
I'm not sure what is wrong w/ circle CI, it cannot apply android library :/.
Btw did you try running tests? I guess this will break as they also create loggers. Can you fix them as well.

**Comment by gmerinojimenez** [comment]
Thanks for pointing it, I've updated the tests.

About CI, I've been investigating and I think it is the gradle plugin, which is 2.0.0-beta5 and I think it has expired. I will try it and if it looks good I will create a different pull request, to don't mix things.

**Comment by yigit** [comment]
sorry I only saw your message this morning. I've already updated the plugin to latest. Also, I don't think it was the problem because it was already building fine.
https://circleci.com/gh/yigit/android-priority-jobqueue/143
So the other CL is not necessary.

**Comment by yigit** [comment]
oh i realize what the problem is. You should be using master not v2. I've already merged into master.

**Comment by gmerinojimenez** [comment]
Ok, I'll close this one then and create a new PR based on master

**Comment by yigit** [comment]
merged the other one.

**Pull request closed without merging**
